### ISSUE TITLE
Cannot quit and install using electron-updater on Windows

### ISSUE THREAD

**Issue by namikingsoft** [namikingsoft/interv-timer#386]
OS:
Windows 10

Version:
v6.0.0-beta.x

Error logs:
C:\Users\namik\AppData\Roaming\interv-timer\logs\main.log

```
[2023-01-09 22:37:47.918] [error] Error: Error: New version 0.6.0-beta.4 is not signed by the application owner: publisherNames: Developer ID Application: T*** N*** (F***), raw info: {
  ...
  "Status": 1,
  "StatusMessage": "証明書チェーンを、信頼されたルート機関として構築できませんでした。"
}
    at Object.h [as newError] (C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:52:10807)
    at Object.task (C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:95:22664)
    at async d.executeDownload (C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:91:16181)
[2023-01-09 22:37:51.374] [info]  Install on explicit quitAndInstall
[2023-01-09 22:37:51.375] [error] Error: Error: No valid update available, can't quit and install
    at d.install (C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:91:17463)
    at d.quitAndInstall (C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:91:16899)
    at C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:95:28469
    at IpcMainImpl.<anonymous> (C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:95:29233)
    at IpcMainImpl.emit (node:events:525:35)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80718)
    at EventEmitter.emit (node:events:513:28)
[2023-01-09 22:37:52.584] [info]  Install on explicit quitAndInstall
[2023-01-09 22:37:52.585] [error] Error: Error: No valid update available, can't quit and install
    at d.install (C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:91:17463)
    at d.quitAndInstall (C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:91:16899)
    at C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:95:28469
    at IpcMainImpl.<anonymous> (C:\Users\namik\AppData\Local\Programs\interv-timer\resources\app.asar\dist\main\main.js:95:29233)
    at IpcMainImpl.emit (node:events:525:35)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80718)
    at EventEmitter.emit (node:events:513:28)
```

**Comment by namikingsoft** [comment]
- Related issue:
  - https://github.com/electron-userland/electron-builder/issues/3269

**Comment by namikingsoft** [comment]
#388 did not fix it.
